[package]
name = "iter_all"
version = "0.1.5"
edition = "2021"
authors = ["Vladas Zakrevksis <146100@gmail.com>"]
description = "Iterate all enum vases"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/VladasZ/iter_all"
repository = "https://github.com/VladasZ/iter_all"

[dependencies]
